name: PR tests
on: pull_request
jobs:
  e2e:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Print event
        run: |
          echo off
          echo '${{ toJson(github.sha) }}'
          echo '${{ toJson(github.event.pull_request) }}'
          echo '${{ toJson(github.event.pull_request.head) }}'

      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      # https://github.com/cypress-io/github-action
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          record: true
        env:
          # pass the Cypress Cloud record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # set custom commit message based on PR title
          COMMIT_INFO_MESSAGE: Tests for PR ${{ github.event.number }} "${{ github.event.pull_request.title }}" Merge ${{ github.event.pull_request.head.sha }} into ${{ github.event.pull_request.base.sha }}
          COMMIT_INFO_SHA: ${{ github.sha }}
          # debug commit info information
          DEBUG: commit-info
